routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/animal', 'AnimalController');
Route::resource('/user','UserController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function animal()
    {
        return $this->hasOne('App\Animal');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/animals/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <a href="{{route('user.index')}}" class="btn btn-primary">Назад</a>
        <hr>
        <ul>
            <li>Animal: {{$animal->name_animal or ''}}</li>
            <li>User name: {{$animal->user->name or ''}}</li>
            <li>User email: {{$animal->user->email or ''}}</li>
        </ul>
    </div>
@endsection

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <form class="form-horizontal" action="{{route('user.store') }}" method="post">
            {{ csrf_field() }}
            <fieldset class="form-horizontal">
                <div class="form-group"><label class="col-sm-2 control-label">Имя:</label>
                    <div class="col-sm-10">
                        <input type="text" name="name" class="form-control" placeholder="" value="{{$user->name or ''}}">
                    </div>
                </div>
                <div class="form-group"><label class="col-sm-2 control-label">E-mail:</label>
                    <div class="col-sm-10">
                        <input type="text" name="email" class="form-control" placeholder="" value="{{$user->email or ''}}">
                    </div>
                </div>
                <div class="form-group"><label class="col-sm-2 control-label">Пароль:</label>
                    <div class="col-sm-10">
                        <input type="password" name="password" class="form-control" placeholder="" value="">
                    </div>
                </div>
                <div class="form-group"><label class="col-sm-2 control-label">Животное:</label>
                    <div class="col-sm-10">
                        <input type="text" name="name_animal" class="form-control" placeholder="" value="">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-4 col-sm-offset-2">
                        <button class="btn btn-primary" type="submit">Сохранить</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <form class="form-horizontal" action="{{route('user.update', $user) }}" method="post">
            <input type="hidden" name="_method" value="put">
            {{ csrf_field() }}
            <fieldset class="form-horizontal">
                <div class="form-group"><label class="col-sm-2 control-label">Имя:</label>
                    <div class="col-sm-10">
                        <input type="text" name="name" class="form-control" placeholder="" value="{{$user->name or ''}}">
                    </div>
                </div>
                <div class="form-group"><label class="col-sm-2 control-label">E-mail:</label>
                    <div class="col-sm-10">
                        <input type="text" name="email" class="form-control" placeholder="" value="{{$user->email or ''}}">
                    </div>
                </div>
                <div class="form-group"><label class="col-sm-2 control-label">Пароль:</label>
                    <div class="col-sm-10">
                        <input type="password" name="password" class="form-control" placeholder="" value="">
                    </div>
                </div>
                <div class="form-group"><label class="col-sm-2 control-label">Животное:</label>
                    <div class="col-sm-10">
                        <input type="text" name="name_animal" class="form-control" placeholder="" value="{{$user->animal->name_animal or ''}}">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-4 col-sm-offset-2">
                        <button class="btn btn-primary" type="submit">Сохранить</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <a href="{{route('user.create')}}" class="btn btn-primary">Создать</a>

        <hr>

        <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15">
            <thead>
            <tr>
                <th data-toggle="true">Имя</th>
                <th data-toggle="true">E-mail</th>
                <th data-hide="phone">Животное</th>
                <th class="text-right" data-sort-ignore="true">Действие</th>
            </tr>
            </thead>
            <tbody>
            @forelse ($users as $user)
                <tr>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>
                        @isset ($user->animal)
                            <a href="{{route('animal.show', $user->animal)}}">{{ $user->animal->name_animal or ''}}</a>
                        @endisset
                    </td>
                    <td class="text-right">
                        <form onsubmit="if(confirm('Удалить?')){ return true }else{ return false }" action="{{route('user.destroy', $user)}}" method="post">
                            <input type="hidden" name="_method" value="DELETE">
                            {{ csrf_field() }}
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{{route('user.edit', $user)}}">Редактировать</a>
                                <button type="submit" class="btn btn-danger">Удалить</button>
                            </div>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" class="text-center">
                        <h2 class="ui center aligned icon header" class="center aligned">
                            <i class="circular database icon"></i>
                            Данные отсутствуют
                        </h2>
                    </td>
                </tr>
            @endforelse

            </tbody>
        </table>
    </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <a href="{{route('user.index')}}" class="btn btn-primary">Назад</a>
        <hr>
        <ul>
            <li>Name: {{$user->name or ''}}</li>
            <li>Email: {{$user->email or ''}}</li>
            <li>Animal: {{$user->animal->name_animal or ''}}</li>
        </ul>
    </div>
@endsection